name: xiaomishop
version: 1.0.0+1
publish_to: none
description: Flutter的练手项目
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter

  # Flutter屏幕适配 PLATFORM ANDROID | IOS | LINUX | MACOS | WEB | WINDOWS
  flutter_screenutil: ^5.9.3

  # 轮播图 PLATFORM ANDROID | IOS | LINUX | MACOS | WEB | WINDOWS
  card_swiper : ^3.0.0

  #日志  PLATFORM ANDROID | IOS | LINUX | MACOS | WEB | WINDOWS
  logger: ^2.3.0

  #网络请求框架  PLATFORM ANDROID | IOS | LINUX | MACOS | WEB | WINDOWS
  dio: ^5.3.1
  #网络请求框架 PLATFORM ANDROID | IOS | LINUX | MACOS | WEB | WINDOWS
  retrofit: ^4.0.1
  #网络状态监听 PLATFORM ANDROID | IOS | LINUX | MACOS | WEB | WINDOWS
  connectivity_plus: ^5.0.1
  #网络响应日志打印框架 PLATFORM ANDROID | IOS | LINUX | MACOS | WEB | WINDOWS
  pretty_dio_logger: ^1.3.1

  #cookie管理 PLATFORM ANDROID | IOS | LINUX | MACOS | WINDOWS
  cookie_jar: ^4.0.8
  #cookie管理 PLATFORM ANDROID | IOS | LINUX | MACOS | WINDOWS
  dio_cookie_manager: ^3.1.1

  # 获取包信息  PLATFORM ANDROID | IOS | LINUX | MACOS | WEB | WINDOWS
  package_info_plus: ^4.1.0
  # 获取设备信息   PLATFORM ANDROID | IOS | LINUX | MACOS | WEB | WINDOWS
  device_info_plus: ^9.0.3

  # 序列化工具  PLATFORM ANDROID | IOS | LINUX | MACOS | WEB | WINDOWS
  json_annotation: ^4.9.0


dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

  # 序列化工具  PLATFORM ANDROID | IOS | LINUX | MACOS | WEB | WINDOWS
  json_serializable: ^6.8.0
  #retrofit框架生成请求  PLATFORM ANDROID | IOS | LINUX | MACOS | WEB | WINDOWS
  retrofit_generator: ^8.1.0
  #运行构建  PLATFORM ANDROID | IOS | LINUX | MACOS | WEB | WINDOWS
  build_runner: ^2.4.9

flutter: 
  uses-material-design: true
  fonts:
    - family: xiaomiIcons   #指定一个字体名 根据自己的需求定义
      fonts:
        - asset: assets/fonts/iconfont.ttf

